# -*- coding: utf-8 -*-
"""Delete_non_books_by_filtering_type.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1avXMsWmMjagfweFcnQohX1r9cagX-0Rq
"""

import mysql.connector

# Connect to the database
conn = mysql.connector.connect(
    host='127.0.0.1',
    user='root',
    password='root',
    database='community_library'
)

cursor = conn.cursor()

# Delete all records that aren't books by filtering Type column
delete_query = """
    DELETE FROM books
    WHERE Type != 'Text' OR Type IS NULL;
"""

cursor.execute(delete_query)
conn.commit()

cursor.close()
conn.close()

print("All records that are not books have been removed from the books table.")