# -*- coding: utf-8 -*-
"""Drop_13_columns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RSitSkC-MyN2V2tmGHnOgxS8moTbgYw1
"""

import mysql.connector

# Connect to the database
conn = mysql.connector.connect(
    host='127.0.0.1',
    user='root',
    password='root',
    database='community_library'
)

cursor = conn.cursor()

# Drop several column
alter_query = """
    ALTER TABLE books
    DROP COLUMN Issued;
    DROP COLUMN Language;
    DROP COLUMN Read online (web);
    DROP COLUMN EPUB3 (E-readers incl. Send-to-Kindle);
    DROP COLUMN EPUB (older E-readers);
    DROP COLUMN EPUB (no images, older E-readers);
    DROP COLUMN Kindle;
    DROP COLUMN Kindle (E-readers incl. Send-to-Kindle);
    DROP COLUMN Kindle (no images, older E-readers);
    DROP COLUMN Plain Text UTF-8;
    DROP COLUMN Download HTML(zip);
    DROP COLUMN Resource Description Framework (RDF);
    DROP COLUMN Other Links;
"""

cursor.execute(alter_query)
conn.commit()

cursor.close()
conn.close()

print("13 Columns have been dropped from the books table.")